hydra:
  run:
    dir: ./output/${parameters.model_name}_${parameters.batch_size}_${parameters.num_epochs}

parameters:
  data_dir: "/data/ntire20-datasetnoise/" 
  resume: "put-ckpt-name"
  ckpt_path: "ckpt"
  logs_path: "log"
  loss: "1.0*L1"
  model_name: "PDANet"
  img_size: 512
  num_epochs: 100
  batch_size: 8
  num_workers: 12
  lr_init: 1.e-3
  lr_step: 25
  lr_gamma: 0.5
  random_seed: 42
  verbose_step: 1000
  requires_grad: True
  inference: False
  optim_reset: False
  in_channel: 4
  out_channel: 3
  scheduler: "plateau"

steplr:
  step_size: 70
  gamma: 0.5

plateau:
  mode: 'min' 
  factor: 0.8
  patience: 1
  verbose: False
  threshold: 0.0001
  threshold_mode: 'abs'
  cooldown: 0
  min_lr: 5.e-6
  eps: 1.e-8

