hydra:
  run:
    dir: ./output/${parameters.model_name}_${parameters.batch_size}_${parameters.num_epochs}

parameters:
  data_dir: "/data/ntire20-datasetnoise/" 
  resume: "put-ckpt-name"
  ckpt_path: "ckpt"
  logs_path: "log"
  loss: "1.0*L1"
  model_name: "MIRNet"
  img_size: 448
  num_epochs: 50
  batch_size: 2
  num_workers: 12
  lr_init: 2.e-4
  lr_step: 100
  lr_gamma: 0.5
  random_seed: 42
  verbose_step: 4000
  requires_grad: True
  inference: False
  optim_reset: False
  in_channel: 4
  out_channel: 3
  scheduler: "step"
  net_verbose: False
  features: 64
  scale: 2
  n_resblocks: 2
  n_resgroups: 1
  bias: True
  kernel_size: 3
  reduction: 8
  dw_type: "antialias"

steplr:
  step_size: 70
  gamma: 0.5

plateau:
  mode: 'min' 
  factor: 0.8
  patience: 1
  verbose: False
  threshold: 0.0001
  threshold_mode: 'abs'
  cooldown: 0
  min_lr: 5.e-6
  eps: 1.e-8

