parameters:
  resume: None
  num_epochs: 100
  batch_size: 64
  num_workers: 12
  data_dir: "./data"
  lr: 0.001
  lr_step: 50
  lr_gamma: 0.1
  weight_decay: 0.0001
  exp_name: "mvp_baseline"
  output_path: "./output"
  loss: "1.0*L1"


