hydra:
  run:
    dir: ./

parameters:
  data_dir: "/data/ntire20-datasetnoise/" 
  resume: "put-ckpt-name"
  ckpt_path: "ckpt"
  logs_path: "log"
  loss: "1.0*L1"
  model_name: "RRDUNet"
  img_size: 512
  num_epochs: 100
  batch_size: 64
  num_workers: 12
  lr_init: 1.e-4
  lr_step: 25
  lr_gamma: 0.5
  random_seed: 42
  verbose_step: 500
  requires_grad: True
  inference: False
  optim_reset: False
  in_channel: 4
  out_channel: 3

test:
  batch_size: 1
  test_dir: "/root/aim20/data/validation/input"
  output_dir: "/root/aim20/submissions/"
  subfile: "rrgnet_vanilla"
  model_name: "RRGNet"
  resume: "epoch_74_val_loss_0.0756_psnr_20.8.pth"
  in_channel: 4
  out_channel: 3
  num_workers: 12
  tta: False